---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read.csv("/Users/marcusthuillier/Desktop/MSiA/Winter_2019/MSIA411/Project/Viz3/2001.csv", sep = ",")

```


```{r}
head(data)
x <- names(data)
data$year <- 2001
```


```{r}

foo = read.csv("/Users/marcusthuillier/Desktop/MSiA/Winter_2019/MSIA411/Project/Viz3/2018.csv", sep = ",")
colnames(foo) <- x
foo$year <- 2018
data <- rbind(data,foo)
```

```{r}
years <- data

```

```{r}
height = read.csv("/Users/marcusthuillier/Desktop/MSiA/Winter_2019/MSIA411/Project/Viz3/HeightData2.csv", sep = ",")

map = read.csv("/Users/marcusthuillier/Desktop/MSiA/Winter_2019/MSIA411/Project/Viz3/MapData2.csv", sep = ",")

```



```{r}
library(dplyr)
count(data,year)
```

```{r}
library(stringr)

years$Player <- sapply(strsplit(as.character(years$Player),"\\\\"), `[`, 1)
```


```{r}
head(years)

```



```{r}
X <- rle(as.character(years$Player))
Y <- cumsum(c(1, X$lengths[-length(X$lengths)]))
new_years <- years[Y, ]

```

```{r}
#height <- height[,c(2:4)]
height_2 = height %>% distinct(Player,Height)

```

```{r}

new_years_2 <- merge(x = new_years, y = height_2, by = "Player", all.x = TRUE)

```

```{r}
#map <- map[,c(3:9)]
map_2 <- map[,c(1,3,4)]

```

```{r}
map_3 = map_2 %>% distinct(Player,birth_state,birth_country)

```

```{r}

new_years_3 <- merge(x = new_years_2, y = map_3, by = "Player", all.x = TRUE)

```











```{r}

new_years_3$birth_country <- as.character(new_years_3$birth_country)

new_years_3$birth_country[new_years_3$birth_country != c("United States")] = "International"

```

```{r}
new_years_4 <- new_years_3[,c(1,3,4,6,7,8,12,13,14,31,32,33,34)]


```


```{r}
write.csv(new_years_3,"Player_data.csv")

```











```{r}
data1 <- read.csv("/Users/marcusthuillier/Desktop/MSiA/Winter_2019/MSIA411/Project/NBA shot log 16-17-regular season/shot log ATL.csv")
```


```{r}
head(data1)
x <- names(data1)
data1$team <- "ATL"
```

```{r}

foo =  read.csv("/Users/marcusthuillier/Desktop/MSiA/Winter_2019/MSIA411/Project/NBA shot log 16-17-regular season/shot log WAS.csv")
#foo <- foo[,-c(22,23)]
#colnames(foo) <- x
foo$team <- "WAS"
data1 <- rbind(data1,foo)
```


```{r}
library(dplyr)
count(data1,team)
```

```{r}
write.csv(data1,"NBA_16_17_team.csv")

```



```{r}
shooting <- read.csv("/Users/marcusthuillier/Desktop/Hoop_Viz/Data/NBA Shooting.csv", sep = ",")

rating <- read.csv("/Users/marcusthuillier/Desktop/Hoop_Viz/Data/Teams by Season.csv", sep = ",")

tomerge <- read.csv("/Users/marcusthuillier/Desktop/Hoop_Viz/Data/Team map.csv", sep = ",")




```

```{r}
tomerge <- tomerge[,c(1,3)]
tomerge <- unique(tomerge)


```

```{r}
new_shooting <- merge(shooting,tomerge,by = "Team",all.x = TRUE)
head(new_shooting)

write.csv(new_shooting,"NBA_shooting_mapped.csv")


```

```{r}

new_rating <- merge(rating,tomerge,by = "Team",all.x = TRUE)
head(new_rating)

write.csv(new_rating,"Teams_by_Season_mapped.csv")






```

```{r}

data <- read.csv("/Users/marcusthuillier/Desktop/Hoop_Viz/Final_Data/Player_data.csv", sep = ",")
head(data)



```
```{r}

data$Height <- gsub("'","",data$Height)
data$Height <- gsub("\"","",data$Height)

```

```{r}
data$size[data$Height == "50" | data$Height == "51" | data$Height == "52" | data$Height == "53" | data$Height == "54" | data$Height == "55" | data$Height == "56" | data$Height == "57" | data$Height == "58" | data$Height == "59" | data$Height == "510" | data$Height == "511" | data$Height == "60"]<-"six_feet_and_under"

data$size[data$Height == "61" | data$Height == "62" | data$Height == "63"]<-"six_feet_one_to_three"

data$size[data$Height == "64" | data$Height == "65" | data$Height == "66"]<-"six_feet_four_to_six"

data$size[data$Height == "67" | data$Height == "68" | data$Height == "69"]<-"six_feet_seven_to_nine"

data$size[data$Height == "610" | data$Height == "611"]<-"six_feet_ten_and_eleven"

data$size[data$Height == "70" | data$Height == "71" | data$Height == "72" | data$Height == "73" | data$Height == "74" | data$Height == "75" | data$Height == "76"]<-"seven_feet_and_above"
```


```{r}
data$Pos[data$Pos == "PG-SG"] <- "PG"
data$Pos[data$Pos == "PG-SF"] <- "PG"
data$Pos[data$Pos == "SG-SF"] <- "SG"
data$Pos[data$Pos == "SG-PF"] <- "SG"
data$Pos[data$Pos == "SF-PF"] <- "SF"
data$Pos[data$Pos == "SF-C"] <- "SF"
data$Pos[data$Pos == "PF-C"] <- "PF"

data$Pos[data$Pos == "C-PF"] <- "C"
data$Pos[data$Pos == "C-SF"] <- "C"
data$Pos[data$Pos == "PF-SF"] <- "PF"
data$Pos[data$Pos == "PF-SG"] <- "PF"
data$Pos[data$Pos == "SF-SG"] <- "SF"
data$Pos[data$Pos == "SF-PG"] <- "SF"
data$Pos[data$Pos == "SG-PG"] <- "SG"




```

```{r}
library(tidyverse)
pos_year <- data %>% 
  group_by(year,Pos) %>%
  summarize(three_perc = 100*sum(made_3P)/sum(attempt_3P), three_made = sum(made_3P), three_att = sum(attempt_3P)) 

head(pos_year)
write.csv(pos_year,"Position_Year.csv")

```

```{r}
height_year <- data %>% 
  group_by(year,size) %>%
  summarize(three_perc = 100*sum(made_3P)/sum(attempt_3P), three_made = sum(made_3P), three_att = sum(attempt_3P)) 

head(height_year)

write.csv(height_year,"Height_Year.csv")

```

```{r}

nation_year <- data %>% 
  group_by(year,birth_country) %>%
  summarize(three_perc = 100*sum(made_3P)/sum(attempt_3P), three_made = sum(made_3P), three_att = sum(attempt_3P)) 

head(nation_year)

write.csv(nation_year,"Nation_Year.csv")

```

```{r}
temp <- data[data$attempt_3P > 50,]

pos_volume_year <- temp %>% 
  group_by(year,Pos) %>% 
  slice(which.max(made_3P))

pos_volume_year$choice <- "Position_Volume" 

pos_perc_year <- temp %>% 
  group_by(year,Pos) %>% 
  slice(which.max(percent_3P))

pos_perc_year$choice <- "Position_Percentage" 

pos_player <- rbind(pos_volume_year,pos_perc_year)
```





```{r}

height_volume_year <- temp %>% 
  group_by(year,size) %>% 
  slice(which.max(made_3P))

height_volume_year$choice <- "Height_Volume" 

height_perc_year <- temp %>% 
  group_by(year,size) %>% 
  slice(which.max(percent_3P))

height_perc_year$choice <- "Height_Percentage" 

height_player <- rbind(height_volume_year,height_perc_year)



```


```{r}
nation_volume_year <- temp %>% 
  group_by(year,birth_country) %>% 
  slice(which.max(made_3P))

nation_volume_year$choice <- "Nation_Volume" 

nation_perc_year <- temp %>% 
  group_by(year,birth_country) %>% 
  slice(which.max(percent_3P))

nation_perc_year$choice <- "Nation_Percentage" 

nation_player <- rbind(nation_volume_year,nation_perc_year)
```


```{r}
player_final <- rbind(pos_player,height_player,nation_player)

write.csv(player_final,"Top_Players.csv")

```

```{r}





```















```{r}
data <- read.csv("/Users/marcusthuillier/Desktop/Hoop_Viz/Data_Files/NBA_shooting_mapped.csv", sep = ",")
head(data)
```

```{r}
test <- data

```

```{r}
test$portion_from_3_corner_total <- 
  test$portion_from_3_corner * test$portion_from_3

test$portion_from_3_top_total <- 
  test$portion_from_3 - test$portion_from_3_corner_total

test$percentage_from_3_corner_total <- test$percentage_from_3_corner

test$percentage_from_3_top_total <- 
  (test$portion_from_3 * test$percentage_from_3 - test$portion_from_3_corner_total * test$percentage_from_3_corner_total) / test$portion_from_3_top_total

```

```{r}

write.csv(test,"NBA_shooting_mapped.csv")

```











